logging:
  level: 
    '[it.infotechconsults]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    # '[org.springframework.security]': TRACE
    # '[org.hibernate.type]': DEBUG

server:
  servlet:
    context-path: /api

spring:
  devtools:
    restart:
      enabled: false

  liquibase:
    change-log: classpath:db/master.xml
    
  datasource:
    url: jdbc:postgresql://localhost:5432/bric48db
    username: dbuser
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
        dialecT: org.hibernate.dialect.PostgreSQLDialect
    