logging:
  level: 
    '[it.infotechconsults]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.springframework.messaging]': DEBUG
    # '[org.springframework.security]': TRACE
    # '[org.hibernate.type]': DEBUG

server:
  servlet:
    context-path: /api

mqtt:
  default-language: it
  broker:
    topic:
      user-near-machinery: user-near-machinery
      user-far-machinery: user-far-machinery
    urL: tcp://${MQTT_HOST:localhost}:${MQTT_PORT:1883}
    client-id: bric48-backend

websocket:
  topic:
    machinery-users: /machinery-users

spring:
  devtools:
    restart:
      enabled: false

  liquibase:
    change-log: classpath:db/master.xml
    
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DBNAME:bric48db}
    username: ${DB_USER:dbuser}
    password: ${DB_PWD:password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
        dialecT: org.hibernate.dialect.PostgreSQLDialect
    