spring:
  liquibase:
    enabled: false
    change-log: classpath:db/master.xml
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bric48db
    username: dbuser
    password: password
    
  datasource:
    url: jdbc:postgresql://localhost:5432/bric48db
    username: dbuser
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialecT: org.hibernate.dialect.PostgreSQLDialect
    